#!/bin/sh /etc/rc.common

START=165

auth_app=device_auth.sh

start() {
    echo 'start device auth'
	$auth_app &
}

stop() {
    echo 'stop device auth'
	killall -9 &auth_app
}

status() {
	echo 'device auth'
}

